//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsFrameworkClientApp.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.InterfaceServer")]
    public interface InterfaceServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServer/sendsToServer", ReplyAction="http://tempuri.org/InterfaceServer/sendsToServerResponse")]
        bool sendsToServer(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServer/sendsToServer", ReplyAction="http://tempuri.org/InterfaceServer/sendsToServerResponse")]
        System.Threading.Tasks.Task<bool> sendsToServerAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServer/getServerString", ReplyAction="http://tempuri.org/InterfaceServer/getServerStringResponse")]
        string getServerString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServer/getServerString", ReplyAction="http://tempuri.org/InterfaceServer/getServerStringResponse")]
        System.Threading.Tasks.Task<string> getServerStringAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfaceServerChannel : FormsFrameworkClientApp.ServiceRef.InterfaceServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceServerClient : System.ServiceModel.ClientBase<FormsFrameworkClientApp.ServiceRef.InterfaceServer>, FormsFrameworkClientApp.ServiceRef.InterfaceServer {
        
        public InterfaceServerClient() {
        }
        
        public InterfaceServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool sendsToServer(string message) {
            return base.Channel.sendsToServer(message);
        }
        
        public System.Threading.Tasks.Task<bool> sendsToServerAsync(string message) {
            return base.Channel.sendsToServerAsync(message);
        }
        
        public string getServerString() {
            return base.Channel.getServerString();
        }
        
        public System.Threading.Tasks.Task<string> getServerStringAsync() {
            return base.Channel.getServerStringAsync();
        }
    }
}
