//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRef
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.InterfaceServer")]
    public interface InterfaceServer
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServer/sendsToServer", ReplyAction="http://tempuri.org/InterfaceServer/sendsToServerResponse")]
        bool sendsToServer(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServer/sendsToServer", ReplyAction="http://tempuri.org/InterfaceServer/sendsToServerResponse")]
        System.Threading.Tasks.Task<bool> sendsToServerAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServer/getServerString", ReplyAction="http://tempuri.org/InterfaceServer/getServerStringResponse")]
        string getServerString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceServer/getServerString", ReplyAction="http://tempuri.org/InterfaceServer/getServerStringResponse")]
        System.Threading.Tasks.Task<string> getServerStringAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface InterfaceServerChannel : ServiceRef.InterfaceServer, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class InterfaceServerClient : System.ServiceModel.ClientBase<ServiceRef.InterfaceServer>, ServiceRef.InterfaceServer
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InterfaceServerClient() : 
                base(InterfaceServerClient.GetDefaultBinding(), InterfaceServerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_InterfaceServer.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceServerClient(EndpointConfiguration endpointConfiguration) : 
                base(InterfaceServerClient.GetBindingForEndpoint(endpointConfiguration), InterfaceServerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceServerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InterfaceServerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceServerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InterfaceServerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool sendsToServer(string message)
        {
            return base.Channel.sendsToServer(message);
        }
        
        public System.Threading.Tasks.Task<bool> sendsToServerAsync(string message)
        {
            return base.Channel.sendsToServerAsync(message);
        }
        
        public string getServerString()
        {
            return base.Channel.getServerString();
        }
        
        public System.Threading.Tasks.Task<string> getServerStringAsync()
        {
            return base.Channel.getServerStringAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_InterfaceServer))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_InterfaceServer))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/MyLocalServer");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InterfaceServerClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_InterfaceServer);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InterfaceServerClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_InterfaceServer);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_InterfaceServer,
        }
    }
}
